# Generated by Django 3.2.4 on 2021-06-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_catalog_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='version',
            field=models.CharField(max_length=255, unique=True, verbose_name='Версия'),
        ),
    ]
