# Generated by Django 3.2.4 on 2021-06-27 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_catalog_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='version',
        ),
        migrations.CreateModel(
            name='VersionDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=255, unique=True, verbose_name='Версия')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.catalog')),
            ],
        ),
    ]
