# Generated by Django 3.2.4 on 2021-06-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210627_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='version',
            field=models.CharField(default='aaaa', max_length=255, unique=True, verbose_name='Версия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='versiondb',
            name='version',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Версия'),
        ),
    ]
