# Generated by Django 3.2.4 on 2021-06-27 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210627_2214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VersionDB',
        ),
    ]
