# Generated by Django 3.2.4 on 2021-06-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_catalog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='version',
        ),
        migrations.AlterField(
            model_name='catalog',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
