# Generated by Django 3.2.4 on 2021-06-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_versiondb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='versiondb',
            options={'verbose_name': 'Версия', 'verbose_name_plural': 'Версии'},
        ),
    ]
