# Generated by Django 3.2.4 on 2021-06-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_versiondb_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versiondb',
            name='version',
            field=models.CharField(max_length=255, verbose_name='Версия'),
        ),
    ]
