# Generated by Django 3.2.4 on 2021-06-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_versiondb_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versiondb',
            name='version',
            field=models.CharField(max_length=255, unique=True, verbose_name='Версия'),
        ),
    ]
