# Generated by Django 3.2.4 on 2021-06-28 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210628_1033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'ordering': ['-created_date'], 'verbose_name': 'Справочник', 'verbose_name_plural': 'Справочники'},
        ),
    ]
