# Generated by Django 3.2.4 on 2021-06-28 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_catalog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'ordering': ['-version'], 'verbose_name': 'Справочник', 'verbose_name_plural': 'Справочники'},
        ),
    ]
