# Generated by Django 3.2.4 on 2021-07-05 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_catalog_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='catalogitem',
            unique_together={('code', 'name_item_catalog')},
        ),
    ]
